"""
database.py
-----------
SQLAlchemy connection setup. The demo runs on a single SQLite file — there is no database
server to configure, no managed instance to keep awake, and nothing to reset between visitors.

Two paths matter:

* the **seed** (``data/demo.sqlite``) — the generated demo dataset, shipped with the code and
  treated as read-only;
* the **working copy** — where the process actually points.

The seed is copied to the working copy at every boot. That is what makes the demo safe to expose:
the surviving write paths (solver jobs, the audit trail, login throttling) still behave normally,
while anything a visitor does is discarded on restart. Nothing anyone types accumulates.

Override with ``DATABASE_URL`` to point at any other SQLAlchemy URL (a persistent file, an
in-memory database for a test); when set, the seed copy is skipped and the URL is used as given.
"""

from __future__ import annotations

import os
import shutil
import tempfile
import logging
from pathlib import Path
from contextlib import contextmanager

# main.py loads the .env (with override) BEFORE importing this module. This fallback only matters
# when database.py is imported directly by a script (the seeder, a one-off query): it does NOT
# override, so whatever is already in the environment stays authoritative.
try:
    from dotenv import load_dotenv
    from env_paths import resolve_env_file

    _env_file = resolve_env_file()
    if _env_file is not None:
        load_dotenv(dotenv_path=_env_file)
except ImportError:
    pass

from sqlalchemy import create_engine, event, text
from sqlalchemy.orm import sessionmaker, Session

logger = logging.getLogger(__name__)

BACKEND_DIR = Path(__file__).resolve().parent

#: The dataset shipped with the code. Generated by ``tools/make_demo_data.py``; never written to.
SEED_DB = Path(os.getenv("DEMO_DB_SEED", "").strip() or (BACKEND_DIR / "data" / "demo.sqlite"))

#: Where the process actually reads and writes. Recreated from SEED_DB on every boot.
WORK_DB = Path(
    os.getenv("DEMO_DB_PATH", "").strip()
    or (Path(tempfile.gettempdir()) / "taktline-demo.sqlite")
)


def _prepare_working_copy() -> str:
    """Copy the seed over the working file and return the URL to open.

    A missing seed is not fatal: an empty file is created and ``create_all`` builds the schema at
    startup, which is exactly the state the seeder itself needs to run against.
    """
    WORK_DB.parent.mkdir(parents=True, exist_ok=True)
    if SEED_DB.is_file():
        shutil.copyfile(SEED_DB, WORK_DB)
        logger.info("[DB] Seed copiado: %s -> %s", SEED_DB.name, WORK_DB)
    else:
        logger.warning("[DB] Seed ausente (%s) — iniciando com banco vazio.", SEED_DB)
    return f"sqlite:///{WORK_DB.as_posix()}"


DATABASE_URL: str = os.getenv("DATABASE_URL", "").strip() or _prepare_working_copy()

engine = None
SessionLocal = None


def _make_engine(url: str):
    # check_same_thread=False: the solver runs on its own thread and opens its own session.
    eng = create_engine(url, connect_args={"check_same_thread": False}, future=True)

    @event.listens_for(eng, "connect")
    def _pragmas(dbapi_conn, _rec):  # noqa: ANN001
        cur = dbapi_conn.cursor()
        # WAL lets the solver thread read while a request writes; busy_timeout turns the
        # "database is locked" error into a short wait, which is all this workload needs.
        cur.execute("PRAGMA journal_mode=WAL")
        cur.execute("PRAGMA busy_timeout=5000")
        cur.execute("PRAGMA foreign_keys=ON")
        cur.close()

    with eng.connect() as conn:
        conn.execute(text("SELECT 1"))
    return eng


try:
    engine = _make_engine(DATABASE_URL)
    SessionLocal = sessionmaker(bind=engine, autocommit=False, autoflush=False)
    logger.info("[DB] Conectado -> %s", DATABASE_URL)
except Exception as exc:  # pragma: no cover — a broken local path, nothing else
    logger.warning("[DB] Falha ao abrir o banco: %s", exc)


def is_available() -> bool:
    if engine is None:
        return False
    try:
        with engine.connect() as conn:
            conn.execute(text("SELECT 1"))
        return True
    except Exception:
        return False


def check_connection() -> tuple[bool, str]:
    if engine is None:
        return False, "Banco de dados não disponível."
    try:
        with engine.connect() as conn:
            conn.execute(text("SELECT 1"))
        return True, "OK"
    except Exception as exc:
        return False, str(exc)


@contextmanager
def get_db() -> Session:  # type: ignore[return]
    if SessionLocal is None:
        raise RuntimeError("Banco de dados nao configurado.")
    db: Session = SessionLocal()
    try:
        yield db
        db.commit()
    except Exception:
        db.rollback()
        raise
    finally:
        db.close()
